name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  php-81:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.1.2'
        tags: 8.1.2,8.1,8,latest
        workdir: 8.1/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
  php-80:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.0.15'
        tags: 8.0.15,8.0
        workdir: 8.0/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
  php-74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '7.4.27'
        tags: 7.4.27,7.4,7
        workdir: 7.4/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
  php-73:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '7.3.33'
        tags: 7.3.33,7.3
        workdir: 7.3/alpine3.15/fpm
        platform: linux/amd64,linux/arm64
